SELECT 
    U.USER_ID,
    U.NICKNAME,
    SUM(B.PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_BOARD AS B
    , USED_GOODS_USER AS U
WHERE B.STATUS = 'DONE' AND U.USER_ID = B.WRITER_ID
GROUP BY U.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC
;