-- 코드를 입력하세요
SELECT 
    A.TITLE, -- 제목
    A.BOARD_ID, -- 게시글 ID
    B.REPLY_ID, -- 댓글 ID
    B.WRITER_ID, -- 댓글 작성자 ID
    B.CONTENTS, -- 댓글 내용
    DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE -- 댓글 작성일
FROM USED_GOODS_BOARD AS A
    JOIN USED_GOODS_REPLY AS B
    ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE LIKE '%2022-10%'
ORDER BY B.CREATED_DATE, A.TITLE
;